@startuml Registration and Authorization Flow
actor "User" as user
participant "Interface" as web
participant "API" as api
database "Database" as db

== Регистрация ==

user -> web: Вводит данные регистрации
web -> api: Отправляет данные формы

group Проверка данных
    alt Некорректные данные
        api -> web: Возврат ошибки валидации
    else Корректные данные
        group Проверка существования пользователя
            api -> db: Поиск пользователя по username
            alt Пользователь существует
                db --> api: Пользователь найден
                api -> web: Ошибка: Username занят
            else Пользователь не найден
                db --> api: Нет такого пользователя
                group Создание нового пользователя
                    api -> db: Сохраняем нового пользователя
                    db --> api: OK
                    api -> web: Регистрация успешна
                end group
            end alt
        end group
    end alt
end group


== Авторизация ==

user -> web: Вводит логин и пароль
web -> api: Отправляет данные авторизации

group Проверка пользователя
    api -> db: Поиск пользователя по username
    alt Пользователь не найден
        db --> api: Нет такого пользователя
        api -> web: Ошибка: Неверный логин или пароль
    else Пользователь найден
        db --> api: Пользователь найден
        group Проверка пароля
            alt Пароль неверный
                api -> web: Ошибка: Неверный логин или пароль
            else Пароль верный
                group Генерация токена
                    api -> api: Генерация JWT токена
                    api -> web: Авторизация успешна + токен
                end group
            end alt
        end group
    end alt
end group

@enduml
